import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it } from 'vitest'
import { App } from './App'
import { AppProviders } from './context/AppProviders'
import { request, session } from './services/http'
import { failure, json, mockBackend, notice, password } from './test/mockBackend'
import { currentSeoulMonth, shiftMonth } from './utils/calendar'

let backend: ReturnType<typeof mockBackend>
beforeEach(() => { backend = mockBackend() })
function renderApp(path = '/recommend') {
  return render(<MemoryRouter initialEntries={[path]}><AppProviders><App /></AppProviders></MemoryRouter>)
}
function input(label: string | RegExp, value: string) { fireEvent.change(screen.getByLabelText(label), { target: { value } }) }
async function ready() {
  await screen.findByRole('heading', { name: '추천 공지' })
  await screen.findByText('시험 공지 1')
  await waitFor(() => expect(screen.getByRole('button', { name: '시험 공지 1 찜 추가' })).toBeEnabled())
}
describe('API-connected app', () => {
  it('protects routes and does not show demo or recovery links', async () => {
    renderApp('/calendar')
    expect(await screen.findByRole('heading', { name: '로그인' })).toBeInTheDocument()
    expect(screen.queryByText(/시연 계정|비밀번호를 잊/)).not.toBeInTheDocument()
  })
  it('normalizes login and restores the server profile', async () => {
    const user = userEvent.setup()
    renderApp('/login')
    input('아이디', ' ALICE ')
    input('비밀번호', password)
    await user.click(screen.getByRole('button', { name: '로그인' }))
    await ready()
    expect(backend.fetcher.mock.calls.some(([, init]) => init?.body === JSON.stringify({ username: 'alice', password }))).toBe(true)
    expect(session.read()?.token).toBe('token-alice')
    expect(JSON.stringify(sessionStorage)).not.toContain(password)
  })
  it('shows wrong-password errors without converting them into server errors', async () => {
    renderApp('/login')
    input('아이디', 'alice'); input('비밀번호', 'wrong')
    fireEvent.click(screen.getByRole('button', { name: '로그인' }))
    expect(await screen.findByText('아이디 또는 비밀번호가 올바르지 않습니다.')).toBeInTheDocument()
  })
  it('validates signup and completes server onboarding', async () => {
    renderApp('/signup')
    input('아이디', '1bad'); input(/^비밀번호$/, 'short'); input('비밀번호 확인', 'different')
    fireEvent.click(screen.getByRole('button', { name: '가입하고 시작하기' }))
    expect(await screen.findByText('비밀번호는 12~128자로 입력해 주세요.')).toBeInTheDocument()
    expect(screen.getByText('비밀번호가 일치하지 않습니다.')).toBeInTheDocument()
    input('아이디', 'New_user'); input(/^비밀번호$/, password); input('비밀번호 확인', password)
    fireEvent.click(screen.getByRole('button', { name: '가입하고 시작하기' }))
    await screen.findByRole('heading', { name: '학적 정보를 알려주세요' })
    fireEvent.click(screen.getByRole('button', { name: '다음' }))
    expect(await screen.findByText('학과를 2~80자로 입력해 주세요.')).toBeInTheDocument()
    input('학과', '인공지능공학부'); input('학년', '6'); input('학적 상태', 'graduating')
    fireEvent.click(screen.getByRole('button', { name: '다음' }))
    await screen.findByRole('button', { name: 'AI·SW선택' })
    fireEvent.click(screen.getByRole('button', { name: '선택 완료' }))
    expect(await screen.findByText('관심 분야를 1개 이상 선택해 주세요.')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'AI·SW선택' }))
    fireEvent.click(screen.getByRole('button', { name: '해커톤선택' }))
    fireEvent.click(screen.getByRole('button', { name: '선택 완료' }))
    expect(await screen.findByRole('heading', { name: '맞춤 설정을 완료했어요' })).toBeInTheDocument()
    expect(screen.getByText('인공지능공학부 · 6학년 · 졸업예정')).toBeInTheDocument()
    expect(backend.users.get('new_user')?.profile.onboarding_complete).toBe(true)
  })
  it('reports duplicate signup and partial signup success correctly', async () => {
    const view = renderApp('/signup')
    input('아이디', 'alice'); input(/^비밀번호$/, password); input('비밀번호 확인', password)
    fireEvent.click(screen.getByRole('button', { name: '가입하고 시작하기' }))
    await screen.findByText('이미 사용 중인 아이디입니다.')
    backend.errors.set('POST /auth/login', failure(503, 'UNAVAILABLE'))
    input('아이디', 'newuser')
    fireEvent.click(screen.getByRole('button', { name: '가입하고 시작하기' }))
    expect(await screen.findByText('가입이 완료되었습니다. 아이디와 비밀번호로 로그인해 주세요.')).toBeInTheDocument()
    expect(backend.users.has('newuser')).toBe(true)
    view.unmount()
  })
  it('restores session on refresh and keeps incomplete users in onboarding', async () => {
    backend.addUser('newuser', false); backend.authenticate('newuser')
    renderApp()
    expect(screen.getByText('로그인 정보를 확인하고 있습니다.')).toBeInTheDocument()
    expect(await screen.findByRole('heading', { name: '학적 정보를 알려주세요' })).toBeInTheDocument()
  })
  it('restores preference drafts after remount', async () => {
    const account = backend.addUser('newuser', false)
    Object.assign(account.profile, { department: '컴퓨터공학과', grade: 2, academic_status: 'enrolled' })
    backend.authenticate('newuser')
    const view = renderApp('/preferences')
    fireEvent.click(await screen.findByRole('button', { name: 'AI·SW선택' }))
    view.unmount()
    renderApp('/preferences')
    expect(await screen.findByRole('button', { name: 'AI·SW선택됨' })).toHaveAttribute('aria-pressed', 'true')
  })
  it('retries restore failures and clears expired sessions', async () => {
    backend.authenticate()
    backend.errors.set('GET /auth/me', failure(503, 'UNAVAILABLE', '점검 중'))
    renderApp()
    await screen.findByText('점검 중')
    expect(session.read()).not.toBeNull()
    backend.errors.clear()
    backend.errors.set('GET /auth/me', failure(401, 'INVALID_SESSION'))
    fireEvent.click(screen.getByRole('button', { name: '다시 시도' }))
    await screen.findByRole('heading', { name: '로그인' })
    expect(session.read()).toBeNull()
  })
  it('logs out through the server and prevents cross-account favorites', async () => {
    backend.authenticate(); backend.users.get('alice')!.favorites.add(1)
    renderApp()
    await screen.findByRole('button', { name: '시험 공지 1 찜 해제' })
    fireEvent.click(screen.getByRole('button', { name: '로그아웃' }))
    await screen.findByRole('heading', { name: '로그인' })
    expect(session.read()).toBeNull()
    input('아이디', 'bob'); input('비밀번호', password)
    fireEvent.click(screen.getByRole('button', { name: '로그인' }))
    await ready()
    expect(screen.getByRole('button', { name: '시험 공지 1 찜 추가' })).toHaveAttribute('aria-pressed', 'false')
    expect(backend.fetcher.mock.calls.some(([url, init]) => String(url).endsWith('/auth/logout') && init?.method === 'POST')).toBe(true)
  })
  it('paginates, debounces search, and sends repeated categories', async () => {
    backend.authenticate(); renderApp(); await ready()
    fireEvent.click(screen.getByRole('button', { name: '다음 페이지' }))
    await screen.findByText('시험 공지 23')
    fireEvent.click(screen.getByRole('button', { name: '교육·특강' }))
    await screen.findByText('시험 공지 1')
    fireEvent.click(screen.getByRole('button', { name: '공모전·대회' }))
    await waitFor(() => expect(backend.fetcher.mock.calls.some(([url]) => String(url).includes('category=education&category=contest'))).toBe(true))
    input('추천 공지 검색', '없는 공지')
    expect(backend.fetcher.mock.calls.some(([url]) => new URL(String(url)).searchParams.get('q') === '없는 공지')).toBe(false)
    expect(await screen.findByText('조건에 맞는 공지가 없습니다')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '필터 초기화' }))
    await screen.findByText('시험 공지 1')
    expect(screen.getByText('1 / 2')).toBeInTheDocument()
  })
  it('loads detail only on open and preserves text benefits and unknown values', async () => {
    backend.authenticate(); renderApp(); await ready()
    expect(backend.fetcher.mock.calls.some(([url]) => /\/notices\/\d+/.test(String(url)))).toBe(false)
    fireEvent.click(screen.getByRole('button', { name: '시험 공지 1 상세 보기' }))
    const dialog = await screen.findByRole('dialog')
    expect(await within(dialog).findByText(/최대 10~20점/)).toBeInTheDocument()
    expect(within(dialog).getByText('일정 미정')).toBeInTheDocument()
    expect(within(dialog).getByRole('link', { name: '원문 보기' })).toHaveAttribute('href', 'https://www.scnu.ac.kr/')
    expect(screen.getAllByText('추천도 2%').length).toBeGreaterThan(0)
  })
  it('rolls back failed bookmarks and keeps successful ones after profile edits', async () => {
    backend.authenticate(); renderApp(); await ready()
    backend.errors.set('POST /bookmarks/1', failure(500, 'FAILED', '저장 실패'))
    fireEvent.click(screen.getByRole('button', { name: '시험 공지 1 찜 추가' }))
    await screen.findByText('저장 실패')
    await waitFor(() => expect(screen.getByRole('button', { name: '시험 공지 1 찜 추가' })).toBeEnabled())
    backend.errors.clear()
    fireEvent.click(screen.getByRole('button', { name: '시험 공지 1 찜 추가' }))
    await waitFor(() => expect(backend.users.get('alice')!.favorites.has(1)).toBe(true))
    fireEvent.click(screen.getByRole('button', { name: '내 정보 수정' }))
    await screen.findByRole('button', { name: 'AI·SW선택됨' })
    input('학과', '인공지능공학부')
    fireEvent.click(screen.getByRole('button', { name: '문화·예술선택' }))
    fireEvent.click(screen.getByRole('button', { name: '저장' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(backend.users.get('alice')!.profile.department).toBe('인공지능공학부')
    expect(backend.users.get('alice')!.favorites.has(1)).toBe(true)
    await waitFor(() => expect(screen.getByRole('button', { name: '시험 공지 1 찜 해제' })).toBeInTheDocument())
  })
  it('preserves an edited draft on version conflict until explicit reload', async () => {
    backend.authenticate(); renderApp(); await ready()
    fireEvent.click(screen.getByRole('button', { name: '내 정보 수정' }))
    await screen.findByRole('button', { name: '저장' })
    input('학과', '내 입력')
    backend.users.get('alice')!.profile.version++
    backend.users.get('alice')!.profile.department = '서버 최신 학과'
    fireEvent.click(screen.getByRole('button', { name: '저장' }))
    await screen.findByRole('button', { name: '최신 정보 다시 불러오기' })
    expect(screen.getByLabelText('학과')).toHaveValue('내 입력')
    expect(screen.getByRole('button', { name: '저장' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '최신 정보 다시 불러오기' }))
    await waitFor(() => expect(screen.getByLabelText('학과')).toHaveValue('서버 최신 학과'))
  })
  it('retains onboarding values on server failure', async () => {
    backend.addUser('newuser', false); backend.authenticate('newuser')
    renderApp('/academic')
    await screen.findByLabelText('학과')
    input('학과', '컴퓨터공학과'); input('학년', '2'); input('학적 상태', 'enrolled')
    backend.errors.set('PUT /profile', failure(500, 'FAILED', '저장 실패'))
    fireEvent.click(screen.getByRole('button', { name: '다음' }))
    await screen.findByText('저장 실패')
    expect(screen.getByLabelText('학과')).toHaveValue('컴퓨터공학과')
    expect(backend.users.get('newuser')!.profile.onboarding_complete).toBe(false)
  })
  it('keeps empty-month navigation and shows complete interval ranges', async () => {
    backend.authenticate()
    const month = currentSeoulMonth()
    const next = shiftMonth(month, 1)
    backend.calendars.set(next, { month: next, timezone: 'Asia/Seoul', end_inclusive: true, undated: [{ notice_id: 2, title: '미정 공지', label: '일정 미정' }],
      events: [{ id: '1:0', notice_id: 1, title: '기간 공지', label: '행사', kind: 'event', start_date: month + '-20', end_date: next + '-03',
        start_time: null, end_time: null, display_start: next + '-01', display_end: next + '-03', is_partial: false, continues_before_month: true, continues_after_month: false }] })
    renderApp('/calendar')
    await screen.findByText('이번 달에 표시할 일정이 없습니다.')
    fireEvent.click(screen.getByRole('button', { name: '다음 달' }))
    expect(await screen.findAllByText('기간 공지')).toHaveLength(3)
    expect(screen.getByText('이전 달부터')).toBeInTheDocument()
    expect(screen.getByText('미정 공지')).toBeInTheDocument()
  })
  it('ignores a stale session response after switching accounts', async () => {
    backend.authenticate()
    renderApp()
    await ready()
    const original = backend.fetcher.getMockImplementation()!
    let resolve!: (response: Response) => void
    backend.fetcher.mockImplementation((url, init) => {
      if (String(url).endsWith('/bookmarks/1') && init?.method === 'POST') return new Promise<Response>((done) => { resolve = done })
      return original(url, init)
    })
    fireEvent.click(screen.getByRole('button', { name: '시험 공지 1 찜 추가' }))
    expect(screen.getByRole('button', { name: '시험 공지 1 찜 해제' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: '로그아웃' }))
    await screen.findByRole('heading', { name: '로그인' })
    input('아이디', 'bob'); input('비밀번호', password)
    fireEvent.click(screen.getByRole('button', { name: '로그인' }))
    await ready()
    await act(async () => { resolve(new Response(null, { status: 204 })) })
    expect(screen.getByText('bob')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: '시험 공지 1 찜 추가' })).toHaveAttribute('aria-pressed', 'false')
    expect(session.read()?.token).toBe('token-bob')
  })
  it('does not replace newer filter results with an older response', async () => {
    backend.authenticate(); renderApp(); await ready()
    const original = backend.fetcher.getMockImplementation()!
    let resolve!: (response: Response) => void
    let signal: AbortSignal | null | undefined
    backend.fetcher.mockImplementation((url, init) => {
      const categories = new URL(String(url)).searchParams.getAll('category')
      if (categories.length === 1 && categories[0] === 'education') {
        signal = init?.signal
        return new Promise<Response>((done) => { resolve = done })
      }
      return original(url, init)
    })
    fireEvent.click(screen.getByRole('button', { name: '교육·특강' }))
    await waitFor(() => expect(resolve).toBeDefined())
    fireEvent.click(screen.getByRole('button', { name: '공모전·대회' }))
    await screen.findByText('시험 공지 2')
    expect(signal?.aborted).toBe(true)
    await act(async () => { resolve(json({ items: [notice(999)], total: 1, page: 1, page_size: 20 })) })
    expect(screen.queryByText('시험 공지 999')).not.toBeInTheDocument()
    expect(screen.getByText('23개')).toBeInTheDocument()
  })
  it('does not clear a new login when an earlier logout finishes late', async () => {
    backend.authenticate(); renderApp(); await ready()
    const original = backend.fetcher.getMockImplementation()!
    let resolve!: (response: Response) => void
    backend.fetcher.mockImplementation((url, init) => {
      if (String(url).endsWith('/auth/logout')) return new Promise<Response>((done) => { resolve = done })
      return original(url, init)
    })
    fireEvent.click(screen.getByRole('button', { name: '로그아웃' }))
    backend.errors.set('GET /profile', failure(401, 'INVALID_SESSION'))
    await act(async () => { await expect(request('/profile')).rejects.toMatchObject({ status: 401 }) })
    await screen.findByRole('heading', { name: '로그인' })
    backend.errors.clear()
    input('아이디', 'bob'); input('비밀번호', password)
    fireEvent.click(screen.getByRole('button', { name: '로그인' }))
    await ready()
    await act(async () => { resolve(new Response(null, { status: 204 })) })
    expect(session.read()?.token).toBe('token-bob')
    expect(await screen.findByRole('heading', { name: '추천 공지' })).toBeInTheDocument()
    expect(screen.getByText('bob')).toBeInTheDocument()
  })
  it('retries initial bookmarks before permitting bookmark changes', async () => {
    backend.authenticate(); backend.users.get('alice')!.favorites.add(1)
    backend.errors.set('GET /bookmarks', failure(503, 'UNAVAILABLE', '찜 조회 실패'))
    renderApp()
    await screen.findByText('찜 조회 실패')
    expect(screen.getByRole('button', { name: '시험 공지 1 찜 추가' })).toBeDisabled()
    backend.errors.clear()
    fireEvent.click(screen.getByRole('button', { name: '찜 다시 불러오기' }))
    await waitFor(() => expect(screen.getByRole('button', { name: '시험 공지 1 찜 해제' })).toBeEnabled())
  })
  it('preserves selected interests on onboarding version conflict', async () => {
    const account = backend.addUser('newuser', false)
    Object.assign(account.profile, { department: '컴퓨터공학과', grade: 2, academic_status: 'enrolled' })
    backend.authenticate('newuser'); renderApp('/preferences')
    fireEvent.click(await screen.findByRole('button', { name: 'AI·SW선택' }))
    fireEvent.click(screen.getByRole('button', { name: '해커톤선택' }))
    account.profile.version++
    fireEvent.click(screen.getByRole('button', { name: '선택 완료' }))
    await screen.findByRole('button', { name: '최신 정보 다시 불러오기' })
    expect(screen.getByRole('button', { name: 'AI·SW선택됨' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('button', { name: '선택 완료' })).toBeDisabled()
    expect(account.profile.onboarding_complete).toBe(false)
  })
})
