"""Initial backend schema

Revision ID: 0001
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.CheckConstraint("type IN ('field','activity')", name=op.f('ck_interests_interest_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interests'))
    )
    op.create_table('leases',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_leases'))
    )
    op.create_table('rate_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window', name=op.f('pk_rate_buckets'))
    )
    with op.batch_alter_table('rate_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_buckets_expires_at'), ['expires_at'], unique=False)

    op.create_table('sources',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('list_url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_sources'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('auth_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("purpose IN ('verify','reset')", name=op.f('ck_auth_tokens_purpose')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_auth_tokens'))
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('crawl_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_crawl_jobs_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_jobs'))
    )
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_jobs_status'), ['status'], unique=False)

    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('image_only', sa.Boolean(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['source_code'], ['sources.code'], name=op.f('fk_notices_source_code_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notices')),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_notices_source_external')
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index('ix_notices_posted_id', ['posted_date', 'id'], unique=False)

    op.create_table('profile_interests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('interest_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_profile_interests_interest_id_interests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_interests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id', name=op.f('pk_profile_interests'))
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('academic_status', sa.String(length=24), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('grade IS NULL OR (grade >= 1 AND grade <= 6)', name=op.f('ck_profiles_grade_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('fk_bookmarks_notice_id_notices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'notice_id', name=op.f('pk_bookmarks'))
    )
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['crawl_jobs.id'], name=op.f('fk_crawl_runs_job_id_crawl_jobs')),
    sa.ForeignKeyConstraint(['source_code'], ['sources.code'], name=op.f('fk_crawl_runs_source_code_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs'))
    )
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_runs_job_id'), ['job_id'], unique=False)

    op.create_table('notice_analyses',
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('deadline_at', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('fk_notice_analyses_notice_id_notices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notice_id', name=op.f('pk_notice_analyses'))
    )
    with op.batch_alter_table('notice_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notice_analyses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notice_analyses_deadline_at'), ['deadline_at'], unique=False)

    # ### end Alembic commands ###

    # Prevent accidental direct Data API access (for example, a Supabase public schema).
    # The trusted backend must connect as the table-owning migration role.
    # Tenant isolation is still enforced by the backend's user-scoped queries.
    if op.get_bind().dialect.name == "postgresql":
        tables = [
            "interests", "leases", "rate_buckets", "sources", "users", "audit_logs",
            "auth_sessions", "auth_tokens", "crawl_jobs", "notices",
            "profile_interests", "profiles", "bookmarks", "crawl_runs", "notice_analyses",
        ]
        for table in tables:
            op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            op.execute(f'REVOKE ALL ON TABLE "{table}" FROM PUBLIC')
        # Supabase-specific roles are optional on a generic PostgreSQL installation.
        op.execute("""
        DO $block$
        DECLARE role_name text; table_name text;
        BEGIN
          FOREACH role_name IN ARRAY ARRAY['anon', 'authenticated'] LOOP
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
              FOREACH table_name IN ARRAY ARRAY[
                'interests','leases','rate_buckets','sources','users','audit_logs',
                'auth_sessions','auth_tokens','crawl_jobs','notices',
                'profile_interests','profiles','bookmarks','crawl_runs','notice_analyses'
              ] LOOP
                EXECUTE format('REVOKE ALL ON TABLE %I FROM %I', table_name, role_name);
              END LOOP;
            END IF;
          END LOOP;
        END $block$;
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_analyses_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_notice_analyses_category'))

    op.drop_table('notice_analyses')
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_runs_job_id'))

    op.drop_table('crawl_runs')
    op.drop_table('bookmarks')
    op.drop_table('profiles')
    op.drop_table('profile_interests')
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index('ix_notices_posted_id')

    op.drop_table('notices')
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_created_at'))

    op.drop_table('crawl_jobs')
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_expires_at'))

    op.drop_table('auth_tokens')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('sources')
    with op.batch_alter_table('rate_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_buckets_expires_at'))

    op.drop_table('rate_buckets')
    op.drop_table('leases')
    op.drop_table('interests')
    # ### end Alembic commands ###
